### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by gsouf** [briankircho/browserjet#4]
Hi,

Tryed to install browserjet through npm, getting an error downloading the release because browserjet.com is down.

Your last commit was in 2011, do you consider maintaining this package or is it abandoned?

**Comment by ssimono** [comment]
Hi,

This package seems abandoned indeed. I did a PR #3 more than a year ago to make it work without  browserjet.com, so feel free to use it if you want to try it out.

**Comment by gsouf** [comment]
Hi @ssimono  Thanks for your input, would you like to fork the project and maintain it?

**Comment by ssimono** [comment]
Hey

I don't think so :disappointed: I just had a look a while ago but I don't feel like maintaining it though.

**Comment by gsouf** [comment]
Ok thank you btw, I will just skip to something else then ;)
